<a href="https://colab.research.google.com/github/charith7287/DA_DS_coding_part-/blob/main/DA_DS_9%7BPandas_Data_Cleaning%7D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/IPL_Matches_Data_2008_2026.csv")
df

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
0,Indian Premier League,2007/08,1.0,18-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,RE Koertzen,AM Saheba,VN Kulkarni,T20,20,6,male,club,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey..."
1,Indian Premier League,2007/08,2.0,19-04-2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,SL Shastri,RB Tiffin,MSS Ranawat,T20,20,6,male,club,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ..."
2,Indian Premier League,2007/08,3.0,19-04-2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,GA Pratapkumar,IL Howell,Unknown,T20,20,6,male,club,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm..."
3,Indian Premier League,2007/08,4.0,20-04-2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,K Hariharan,Asad Rauf,F Gomes,T20,20,6,male,club,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S..."
4,Indian Premier League,2007/08,5.0,20-04-2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,DJ Harper,AV Jayaprakash,SN Bandekar,T20,20,6,male,club,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,Indian Premier League,2026,70.0,24-05-2026,Kolkata,"Eden Gardens, Kolkata",Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,...,HAS Khalid,SJ Nogajski,M Krishnadas,T20,20,6,male,club,"Kuldeep Yadav, Abishek Porel, KL Rahul, SU Par...","SP Narine, AM Rahane, FH Allen, MK Pandey, C G..."
1239,Indian Premier League,2026,NaN,26-05-2026,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Gujarat Titans,Gujarat Titans,field,...,VK Sharma,Nitin Menon,KN Ananthapadmanabhan,T20,20,6,male,club,"R Shepherd, VR Iyer, V Kohli, D Padikkal, RM P...","K Khejroliya, B Sai Sudharsan, Shubman Gill, J..."
1240,Indian Premier League,2026,NaN,27-05-2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,...,UV Gandhe,R Pandit,SJ Nogajski,T20,20,6,male,club,"YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Par...","PP Hinge, Abhishek Sharma, TM Head, Ishan Kish..."
1241,Indian Premier League,2026,NaN,29-05-2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,bat,...,SJ Nogajski,AT Holdstock,UV Gandhe,T20,20,6,male,club,"TU Deshpande, YBK Jaiswal, V Suryavanshi, Dhru...","Mohammed Siraj, B Sai Sudharsan, Shubman Gill,..."
1242,Indian Premier League,2026,NaN,31-05-2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,...,Nitin Menon,J Madanagopal,VK Sharma,T20,20,6,male,club,"M Prasidh Krishna, B Sai Sudharsan, Shubman Gi...","JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Pat..."

In [ ]:
df.columns

Index(['event_name', 'season', 'match_number', 'date', 'city', 'venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'team1_runs',
       'team1_wickets', 'team2_runs', 'team2_wickets', 'winner', 'result_type',
       'win_by_runs', 'win_by_wickets', 'player_of_match', 'match_referee',
       'umpire1', 'umpire2', 'tv_umpire', 'reserve_umpire', 'match_type',
       'overs_limit', 'balls_per_over', 'gender', 'team_type', 'team1_players',
       'team2_players'],
      dtype='object')

In [ ]:
df.shape

(1243, 31)

#Missing Values

In [ ]:
df.isnull().sum()

event_name          0
season              0
match_number       74
date                0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets       0
team2_runs          0
team2_wickets       0
winner             25
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     9
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
match_type          0
overs_limit         0
balls_per_over      0
gender              0
team_type           0
team1_players       0
team2_players       0
dtype: int64

#Select a Column

In [ ]:
#select a column
df["venue"]

0                                   M Chinnaswamy Stadium
1              Punjab Cricket Association Stadium, Mohali
2                                        Feroz Shah Kotla
3                                            Eden Gardens
4                                        Wankhede Stadium
                              ...
1238                                Eden Gardens, Kolkata
1239    Himachal Pradesh Cricket Association Stadium, ...
1240    Maharaja Yadavindra Singh International Cricke...
1241    Maharaja Yadavindra Singh International Cricke...
1242                     Narendra Modi Stadium, Ahmedabad
Name: venue, Length: 1243, dtype: object

In [ ]:
df['player_of_match']

0         BB McCullum
1          MEK Hussey
2         MF Maharoof
3           DJ Hussey
4          MV Boucher
            ...
1238    Kuldeep Yadav
1239       RM Patidar
1240    V Suryavanshi
1241     Shubman Gill
1242          V Kohli
Name: player_of_match, Length: 1243, dtype: object

#Select a Rows With iloc

In [ ]:
df.iloc[0:10]

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
0,Indian Premier League,2007/08,1.0,18-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,RE Koertzen,AM Saheba,VN Kulkarni,T20,20,6,male,club,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey..."
1,Indian Premier League,2007/08,2.0,19-04-2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,SL Shastri,RB Tiffin,MSS Ranawat,T20,20,6,male,club,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ..."
2,Indian Premier League,2007/08,3.0,19-04-2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,GA Pratapkumar,IL Howell,Unknown,T20,20,6,male,club,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm..."
3,Indian Premier League,2007/08,4.0,20-04-2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,K Hariharan,Asad Rauf,F Gomes,T20,20,6,male,club,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S..."
4,Indian Premier League,2007/08,5.0,20-04-2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,DJ Harper,AV Jayaprakash,SN Bandekar,T20,20,6,male,club,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli..."
5,Indian Premier League,2007/08,6.0,21-04-2008,Jaipur,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,...,RB Tiffin,I Shivram,MSS Ranawat,T20,20,6,male,club,"M Kaif, Kamran Akmal, YK Pathan, SR Watson, DS...","K Goel, JR Hopes, KC Sangakkara, DPMD Jayaward..."
6,Indian Premier League,2007/08,7.0,22-04-2008,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,...,AM Saheba,MR Benson,C Shamshuddin,T20,20,6,male,club,"AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...","G Gambhir, V Sehwag, S Dhawan, Shoaib Malik, K..."
7,Indian Premier League,2007/08,8.0,23-04-2008,Chennai,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,...,GA Pratapkumar,BF Bowden,S Ravi,T20,20,6,male,club,"PA Patel, ML Hayden, MEK Hussey, SK Raina, MS ...","L Ronchi, ST Jayasuriya, RV Uthappa, SM Polloc..."
8,Indian Premier League,2007/08,9.0,24-04-2008,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,...,MR Benson,SL Shastri,C Shamshuddin,T20,20,6,male,club,"AC Gilchrist, VVS Laxman, Shahid Afridi, A Sym...","Kamran Akmal, GC Smith, YK Pathan, SR Watson, ..."
9,Indian Premier League,2007/08,10.0,25-04-2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,...,AM Saheba,RE Koertzen,HS Sekhon,T20,20,6,male,club,"K Goel, IK Pathan, KC Sangakkara, Yuvraj Singh...","L Ronchi, ST Jayasuriya, RV Uthappa, DJ Bravo,..."

In [ ]:
df.iloc[0:20,0:5]

               event_name   season  match_number        date        city
0   Indian Premier League  2007/08           1.0  18-04-2008   Bangalore
1   Indian Premier League  2007/08           2.0  19-04-2008  Chandigarh
2   Indian Premier League  2007/08           3.0  19-04-2008       Delhi
3   Indian Premier League  2007/08           4.0  20-04-2008     Kolkata
4   Indian Premier League  2007/08           5.0  20-04-2008      Mumbai
5   Indian Premier League  2007/08           6.0  21-04-2008      Jaipur
6   Indian Premier League  2007/08           7.0  22-04-2008   Hyderabad
7   Indian Premier League  2007/08           8.0  23-04-2008     Chennai
8   Indian Premier League  2007/08           9.0  24-04-2008   Hyderabad
9   Indian Premier League  2007/08          10.0  25-04-2008  Chandigarh
10  Indian Premier League  2007/08          11.0  26-04-2008     Chennai
11  Indian Premier League  2007/08          12.0  26-04-2008   Bangalore
12  Indian Premier League  2007/08          13.0  27-04-2008  Chandigarh
13  Indian Premier League  2007/08          14.0  27-04-2008      Mumbai
14  Indian Premier League  2007/08          15.0  28-04-2008   Bangalore
15  Indian Premier League  2007/08          16.0  29-04-2008     Kolkata
16  Indian Premier League  2007/08          17.0  30-04-2008       Delhi
17  Indian Premier League  2007/08          18.0  01-05-2008      Jaipur
18  Indian Premier League  2007/08          19.0  01-05-2008   Hyderabad
19  Indian Premier League  2007/08          20.0  02-05-2008     Chennai

#Filtering Data

In [ ]:
#Filtering data
df[df["city"]=="Bangalore"]

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
0,Indian Premier League,2007/08,1.0,18-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,RE Koertzen,AM Saheba,VN Kulkarni,T20,20,6,male,club,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey..."
11,Indian Premier League,2007/08,12.0,26-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,...,IL Howell,GA Pratapkumar,SK Tarapore,T20,20,6,male,club,"S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...","GC Smith, M Rawat, YK Pathan, SR Watson, M Kai..."
14,Indian Premier League,2007/08,15.0,28-04-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,...,RB Tiffin,K Hariharan,Unknown,T20,20,6,male,club,"B Chipli, W Jaffer, LRPL Taylor, JH Kallis, MV...","PA Patel, ML Hayden, MEK Hussey, SK Raina, MS ..."
20,Indian Premier League,2007/08,21.0,03-05-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers,field,...,SL Shastri,SK Tarapore,CK Nandan,T20,20,6,male,club,"B Chipli, W Jaffer, V Kohli, JH Kallis, Misbah...","AC Gilchrist, VVS Laxman, HH Gibbs, RG Sharma,..."
24,Indian Premier League,2007/08,25.0,05-05-2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,...,BR Doctrove,SL Shastri,SK Tarapore,T20,20,6,male,club,"W Jaffer, V Kohli, CL White, JH Kallis, R Drav...","SE Marsh, JR Hopes, RR Sarwan, Yuvraj Singh, D..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,Indian Premier League,2017,31.0,27-04-2017,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,...,C Shamshuddin,M Erasmus,R Pandit,T20,20,6,male,club,"CH Gayle, V Kohli, AB de Villiers, TM Head, KM...","Ishan Kishan, BB McCullum, SK Raina, AJ Finch,..."
618,Indian Premier League,2017,43.0,05-05-2017,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,field,...,C Shamshuddin,AY Dandekar,N Pandit,T20,20,6,male,club,"Mandeep Singh, CH Gayle, V Kohli, AB de Villie...","HM Amla, MJ Guptill, SE Marsh, M Vohra, WP Sah..."
621,Indian Premier League,2017,46.0,07-05-2017,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,...,C Shamshuddin,CB Gaffaney,N Pandit,T20,20,6,male,club,"CH Gayle, Mandeep Singh, V Kohli, AB de Villie...","CA Lynn, SP Narine, C de Grandhomme, G Gambhir..."
633,Indian Premier League,2017,NaN,17-05-2017,Bangalore,M Chinnaswamy Stadium,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,...,Nitin Menon,A Nand Kishore,KN Ananthapadmanabhan,T20,20,6,male,club,"DA Warner, S Dhawan, KS Williamson, Yuvraj Sin...","RV Uthappa, CA Lynn, YK Pathan, G Gambhir, IR ..."
634,Indian Premier League,2017,NaN,19-05-2017,Bangalore,M Chinnaswamy Stadium,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,field,...,Nitin Menon,C Shamshuddin,KN Ananthapadmanabhan,T20,20,6,male,club,"LMP Simmons, PA Patel, AT Rayudu, RG Sharma, K...","CA Lynn, SP Narine, G Gambhir, RV Uthappa, IR ..."

#1)display the stats ,while chasing rbc won.

In [ ]:
sort_winner=[df["team2"]=="Royal Challengers Bangalore"]

In [ ]:
df[sort_winner[0] & (df['winner'] == 'Royal Challengers Bangalore')]

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
4,Indian Premier League,2007/08,5.0,20-04-2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,DJ Harper,AV Jayaprakash,SN Bandekar,T20,20,6,male,club,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli..."
45,Indian Premier League,2007/08,46.0,21-05-2008,Chennai,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,...,I Shivram,BR Doctrove,S Ravi,T20,20,6,male,club,"PA Patel, SP Fleming, MS Dhoni, SK Raina, S Ba...","JH Kallis, SP Goswami, V Kohli, R Dravid, Misb..."
49,Indian Premier League,2007/08,51.0,25-05-2008,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers,bat,...,RE Koertzen,GA Pratapkumar,Unknown,T20,20,6,male,club,"AC Gilchrist, HH Gibbs, RG Sharma, LPC Silva, ...","JH Kallis, W Jaffer, Misbah-ul-Haq, R Dravid, ..."
128,Indian Premier League,2009/10,14.0,20-03-2010,Mumbai,Brabourne Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,SS Hazare,SK Tarapore,SN Bandekar,T20,20,6,male,club,"ST Jayasuriya, SR Tendulkar, AP Tare, SS Tiwar...","MK Pandey, JH Kallis, RV Uthappa, V Kohli, EJG..."
145,Indian Premier League,2009/10,31.0,02-04-2010,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,bat,...,M Erasmus,AM Saheba,C Shamshuddin,T20,20,6,male,club,"SE Marsh, MS Bisla, KC Sangakkara, RS Bopara, ...","MK Pandey, JH Kallis, KP Pietersen, V Kohli, R..."
163,Indian Premier League,2009/10,49.0,14-04-2010,Jaipur,Sawai Mansingh Stadium,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,...,S Ravi,SK Tarapore,K Sharma,T20,20,6,male,club,"MJ Lumb, NV Ojha, AG Paunikar, SR Watson, AA J...","MK Pandey, JH Kallis, KP Pietersen, RV Uthappa..."
177,Indian Premier League,2011,3.0,09-04-2011,Kochi,Nehru Stadium,Kochi Tuskers Kerala,Royal Challengers Bangalore,Kochi Tuskers Kerala,bat,...,K Hariharan,AL Hill,KN Ananthapadmanabhan,T20,20,6,male,club,"BB McCullum, VVS Laxman, DPMD Jayawardene, BJ ...","MA Agarwal, TM Dilshan, V Kohli, AB de Villier..."
197,Indian Premier League,2011,24.0,22-04-2011,Kolkata,Eden Gardens,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,RB Tiffin,Aleem Dar,S Das,T20,20,6,male,club,"JH Kallis, BJ Haddin, G Gambhir, YK Pathan, EJ...","TM Dilshan, CH Gayle, V Kohli, AB de Villiers,..."
203,Indian Premier League,2011,30.0,26-04-2011,Delhi,Feroz Shah Kotla,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,RJ Tucker,PR Reiffel,AK Chaudhary,T20,20,6,male,club,"DA Warner, V Sehwag, JR Hopes, MS Wade, Y Venu...","CH Gayle, TM Dilshan, V Kohli, AB de Villiers,..."
228,Indian Premier League,2011,55.0,11-05-2011,Jaipur,Sawai Mansingh Stadium,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,K Hariharan,SJA Taufel,R Subramanian,T20,20,6,male,club,"SR Watson, R Dravid, AM Rahane, J Botha, LRPL ...","CH Gayle, TM Dilshan, V Kohli, AB de Villiers,..."
272,Indian Premier League,2012,25.0,20-04-2012,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,RJ Tucker,JD Cloete,B Vij,T20,20,6,male,club,"N Saini, PC Valthaty, SE Marsh, DJ Hussey, DA ...","MA Agarwal, CH Gayle, V Kohli, SS Tiwary, AB d..."
277,Indian Premier League,2012,30.0,23-04-2012,Jaipur,Sawai Mansingh Stadium,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,field,...,S Asnani,S Das,PK Khakhar,T20,20,6,male,club,"R Dravid, AM Rahane, OA Shah, SP Goswami, BJ H...","V Kohli, TM Dilshan, MA Agarwal, CH Gayle, AB ..."
299,Indian Premier League,2012,54.0,09-05-2012,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,VA Kulkarni,SK Tarapore,RM Deshpande,T20,20,6,male,club,"JEC Franklin, SR Tendulkar, RG Sharma, KD Kart...","TM Dilshan, CH Gayle, V Kohli, AB de Villiers,..."
302,Indian Premier League,2012,57.0,11-05-2012,Pune,Subrata Roy Sahara Stadium,Pune Warriors,Royal Challengers Bangalore,Pune Warriors,field,...,SK Tarapore,VA Kulkarni,NA Patwardhan,T20,20,6,male,club,"MD Mishra, MJ Clarke, MK Pandey, RV Uthappa, A...","CH Gayle, TM Dilshan, V Kohli, SS Tiwary, AB d..."
312,Indian Premier League,2012,67.0,17-05-2012,Delhi,Feroz Shah Kotla,Delhi Daredevils,Royal Challengers Bangalore,Delhi Daredevils,field,...,C Shamshuddin,BNJ Oxenford,R Risodkar,T20,20,6,male,club,"UBT Chand, DA Warner, Y Venugopal Rao, DPMD Ja...","CH Gayle, TM Dilshan, V Kohli, AB de Villiers,..."
367,Indian Premier League,2013,46.0,02-05-2013,Pune,Subrata Roy Sahara Stadium,Pune Warriors,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,...,C Shamshuddin,Subroto Das,PG Pathak,T20,20,6,male,club,"RV Uthappa, AJ Finch, TL Suman, Yuvraj Singh, ...","SS Tiwary, CH Gayle, V Kohli, AB de Villiers, ..."
378,Indian Premier League,2013,57.0,10-05-2013,Delhi,Feroz Shah Kotla,Delhi Daredevils,Royal Challengers Bangalore,Delhi Daredevils,field,...,K Srinath,VA Kulkarni,K Bharatan,T20,20,6,male,club,"DPMD Jayawardene, V Sehwag, UBT Chand, DA Warn...","CA Pujara, CH Gayle, V Kohli, MC Henriques, AB..."
399,Indian Premier League,2014,2.0,17-04-2014,Unknown,Sharjah Cricket Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Ravi,VA Kulkarni,K Bharatan,T20,20,6,male,club,"MA Agarwal, M Vijay, KD Karthik, MK Tiwary, JP...","PA Patel, NJ Maddinson, V Kohli, Yuvraj Singh,..."
439,Indian Premier League,2014,42.0,18-05-2014,Ranchi,JSCA International Stadium Complex,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,bat,...,C Shamshuddin,RM Deshpande,J Madanagopal,T20,20,6,male,club,"DR Smith, BB McCullum, SK Raina, DJ Hussey, MS...","CH Gayle, PA Patel, V Kohli, AB de Villiers, Y..."
462,Indian Premier League,2015,5.0,11-04-2015,Kolkata,Eden Gardens,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,C Shamshuddin,PG Pathak,VK Sharma,T20,20,6,male,club,"RV Uthappa, G Gambhir, MK Pandey, SA Yadav, YK...","CH Gayle, V Kohli, KD Karthik, Mandeep Singh, ..."
479,Indian Premier League,2015,22.0,24-04-2015,Ahmedabad,"Sardar Patel Stadium, Motera",Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Ravi,AK Chaudhary,K Srinath,T20,20,6,male,club,"AM Rahane, SR Watson, SPD Smith, KK Nair, DJ H...","CH Gayle, V Kohli, AB de Villiers, Mandeep Sin..."
482,Indian Premier League,2015,26.0,26-04-2015,Delhi,Feroz Shah Kotla,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Ravi,AK Chaudhary,K Srinath,T20,20,6,male,club,"MA Agarwal, SS Iyer, JP Duminy, Yuvraj Singh, ...","CH Gayle, V Kohli, AB de Villiers, Mandeep Sin..."
502,Indian Premier League,2015,46.0,10-05-2015,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,...,C Shamshuddin,K Srinath,PG Pathak,T20,20,6,male,club,"PA Patel, LMP Simmons, RG Sharma, KA Pollard, ...","CH Gayle, V Kohli, AB de Villiers, KD Karthik,..."
508,Indian Premier League,2015,52.0,15-05-2015,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,...,HDPK Dharmasena,K Srinath,A Nand Kishore,T20,20,6,male,club,"DA Warner, S Dhawan, MC Henriques, EJG Morgan,...","CH Gayle, V Kohli, AB de Villiers, Mandeep Sin..."
532,Indian Premier League,2016,16.0,22-04-2016,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiants,Royal Challengers Bangalore,Rising Pune Supergiants,field,...,VK Sharma,KN Ananthapadmanabhan,YC Barde,T20,20,6,male,club,"AM Rahane, F du Plessis, KP Pietersen, SPD Smi...","V Kohli, KL Rahul, AB de Villiers, SR Watson, ..."
555,Indian Premier League,2016,39.0,09-05-2016,Chandigarh,"Punjab Cricket Association IS Bindra Stadium, ...",Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,field,...,HDPK Dharmasena,CK Nandan,R Pandit,T20,20,6,male,club,"HM Amla, M Vijay, WP Saha, DA Miller, MP Stoin...","V Kohli, KL Rahul, AB de Villiers, SR Watson, ..."
564,Indian Premier League,2016,48.0,16-05-2016,Kolkata,Eden Gardens,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,A Nand Kishore,BNJ Oxenford,YC Barde,T20,20,6,male,club,"RV Uthappa, G Gambhir, MK Pandey, YK Pathan, A...","CH Gayle, V Kohli, AB de Villiers, SR Watson, ..."
572,Indian Premier League,2016,56.0,22-05-2016,Raipur,Shaheed Veer Narayan Singh International Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,BNJ Oxenford,VK Sharma,YC Barde,T20,20,6,male,club,"Q de Kock, RR Pant, KK Nair, SV Samson, SW Bil...","CH Gayle, V Kohli, AB de Villiers, KL Rahul, S..."
573,Indian Premier League,2016,NaN,24-05-2016,Bangalore,M Chinnaswamy Stadium,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,HDPK Dharmasena,BNJ Oxenford,A Deshmukh,T20,20,6,male,club,"AJ Finch, BB McCullum, SK Raina, KD Karthik, D...","CH Gayle, V Kohli, AB de Villiers, KL Rahul, S..."
596,Indian Premier League,2017,20.0,18-04-2017,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Royal Challengers Bangalore,Gujarat Lions,field,...,VK Sharma,A Nand Kishore,Navdeep Singh,T20,20,6,male,club,"DR Smith, BB McCullum, SK Raina, AJ Finch, KD ...","CH Gayle, V Kohli, TM Head, KM Jadhav, SR Wats..."
631,Indian Premier League,2017,56.0,14-05-2017,Delhi,Feroz Shah Kotla,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,...,C Shamshuddin,KN Ananthapadmanabhan,R Pandit,T20,20,6,male,club,"SV Samson, KK Nair, SS Iyer, RR Pant, MN Samue...","CH Gayle, Vishnu Vinod, V Kohli, TM Head, KM J..."
643,Indian Premier League,2018,8.0,13-04-2018,Bengaluru,M.Chinnaswamy Stadium,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Ravi,C Shamshuddin,K Srinath,T20,20,6,male,club,"KL Rahul, MA Agarwal, AJ Finch, Yuvraj Singh, ...","Q de Kock, BB McCullum, V Kohli, AB de Villier..."
654,Indian Premier League,2018,19.0,21-04-2018,Bengaluru,M.Chinnaswamy Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,CK Nandan,A Nand Kishore,UV Gandhe,T20,20,6,male,club,"JJ Roy, G Gambhir, SS Iyer, RR Pant, GJ Maxwel...","Q de Kock, M Vohra, V Kohli, AB de Villiers, C..."
680,Indian Premier League,2018,45.0,12-05-2018,Delhi,Arun Jaitley Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,HDPK Dharmasena,AK Chaudhary,K Srinath,T20,20,6,male,club,"PP Shaw, JJ Roy, SS Iyer, RR Pant, V Shankar, ...","PA Patel, MM Ali, V Kohli, AB de Villiers, Man..."
683,Indian Premier League,2018,48.0,14-05-2018,Indore,Holkar Cricket Stadium,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,VK Sharma,CK Nandan,GR Sadashiv Iyer,T20,20,6,male,club,"KL Rahul, CH Gayle, KK Nair, AJ Finch, MP Stoi...","V Kohli, PA Patel, MM Ali, AB de Villiers, Man..."
723,Indian Premier League,2019,28.0,13-04-2019,Chandigarh,Punjab Cricket Association IS Bindra Stadium,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,UV Gandhe,NJ Llong,K Srinath,T20,20,6,male,club,"KL Rahul, CH Gayle, MA Agarwal, SN Khan, SM Cu...","PA Patel, V Kohli, AB de Villiers, MP Stoinis,..."
749,Indian Premier League,2019,54.0,04-05-2019,Bengaluru,M.Chinnaswamy Stadium,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,NJ Llong,UV Gandhe,Unknown,T20,20,6,male,club,"WP Saha, MJ Guptill, MK Pandey, KS Williamson,...","PA Patel, V Kohli, AB de Villiers, SO Hetmyer,..."
770,Indian Premier League,2020/21,15.0,03-10-2020,Abu Dhabi,Sheikh Zayed Stadium,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,...,S Ravi,PG Pathak,UV Gandhe,T20,20,6,male,club,"JC Buttler, SPD Smith, SV Samson, RV Uthappa, ...","D Padikkal, AJ Finch, V Kohli, AB de Villiers,..."
788,Indian Premier League,2020/21,33.0,17-10-2020,Unknown,Dubai International Cricket Stadium,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,...,Nitin Menon,PR Reiffel,YC Barde,T20,20,6,male,club,"RV Uthappa, BA Stokes, SV Samson, SPD Smith, J...","D Padikkal, AJ Finch, V Kohli, AB de Villiers,..."
794,Indian Premier League,2020/21,39.0,21-10-2020,Abu Dhabi,Sheikh Zayed Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,...,S Ravi,CB Gaffaney,UV Gandhe,T20,20,6,male,club,"Shubman Gill, RA Tripathi, N Rana, T Banton, K...","D Padikkal, AJ Finch, Gurkeerat Singh, V Kohli..."
816,Indian Premier League,2021,1.0,09-04-2021,Chennai,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,Nitin Menon,C Shamshuddin,UV Gandhe,T20,20,6,male,club,"RG Sharma, CA Lynn, SA Yadav, Ishan Kishan, HH...","Washington Sundar, V Kohli, RM Patidar, GJ Max..."
831,Indian Premier League,2021,16.0,22-04-2021,Mumbai,"Wankhede Stadium, Mumbai",Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Ravi,VK Sharma,AY Dandekar,T20,20,6,male,club,"JC Buttler, M Vohra, SV Samson, DA Miller, S D...","V Kohli, D Padikkal, GJ Maxwell, AB de Villier..."
858,Indian Premier League,2021,43.0,29-09-2021,Dubai,Dubai International Cricket Stadium,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,KN Ananthapadmanabhan,RK Illingworth,K Srinivasan,T20,20,6,male,club,"E Lewis, YBK Jaiswal, SV Samson, MK Lomror, LS...","V Kohli, D Padikkal, KS Bharat, GJ Maxwell, AB..."
871,Indian Premier League,2021,56.0,08-10-2021,Dubai,Dubai International Cricket Stadium,Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,Nitin Menon,K Srinivasan,Navdeep Singh,T20,20,6,male,club,"PP Shaw, S Dhawan, RR Pant, SS Iyer, SO Hetmye...","V Kohli, D Padikkal, KS Bharat, AB de Villiers..."
881,Indian Premier League,2022,6.0,30-03-2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,Navdeep Singh,Nitin Menon,Chirra Ravikanthreddy,T20,20,6,male,club,"AM Rahane, VR Iyer, SS Iyer, N Rana, SP Narine...","F du Plessis, Anuj Rawat, V Kohli, DJ Willey, ..."
888,Indian Premier League,2022,13.0,05-04-2022,Mumbai,"Wankhede Stadium, Mumbai",Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,HAS Khalid,Nitin Menon,NA Patwardhan,T20,20,6,male,club,"JC Buttler, YBK Jaiswal, D Padikkal, SV Samson...","F du Plessis, Anuj Rawat, V Kohli, DJ Willey, ..."
893,Indian Premier League,2022,18.0,09-04-2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,KN Ananthapadmanabhan,UV Gandhe,Vinod Seshan,T20,20,6,male,club,"Ishan Kishan, RG Sharma, D Brevis, SA Yadav, T...","F du Plessis, Anuj Rawat, V Kohli, KD Karthik,..."
942,Indian Premier League,2022,67.0,19-05-2022,Mumbai,"Wankhede Stadium, Mumbai",Gujarat Titans,Royal Challengers Bangalore,Gujarat Titans,bat,...,GR Sadashiv Iyer,Navdeep Singh,Tapan Sharma,T20,20,6,male,club,"WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ...","V Kohli, F du Plessis, GJ Maxwell, KD Karthik,..."
954,Indian Premier League,2023,5.0,02-04-2023,Bengaluru,"M Chinnaswamy Stadium, Bengaluru",Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,Tapan Sharma,VK Sharma,A Bengeri,T20,20,6,male,club,"JP Behrendorff, RG Sharma, Ishan Kishan, C Gre...","V Kohli, F du Plessis, KD Karthik, GJ Maxwell,..."
1014,Indian Premier League,2023,65.0,18-05-2023,Hyderabad,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,VK Sharma,HAS Khalid,VM Dhokre,T20,20,6,male,club,"T Natarajan, Abhishek Sharma, RA Tripathi, AK ...","V Kohli, F du Plessis, GJ Maxwell, MG Bracewel..."

Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.

#2) Display V kohli , how many matches he won player of the match

In [ ]:
df[df['player_of_match'] == 'V Kohli']

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
203,Indian Premier League,2011,30.0,26-04-2011,Delhi,Feroz Shah Kotla,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,RJ Tucker,PR Reiffel,AK Chaudhary,T20,20,6,male,club,"DA Warner, V Sehwag, JR Hopes, MS Wade, Y Venu...","CH Gayle, TM Dilshan, V Kohli, AB de Villiers,..."
208,Indian Premier League,2011,35.0,29-04-2011,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,...,SS Hazare,RB Tiffin,CK Nandan,T20,20,6,male,club,"CH Gayle, TM Dilshan, V Kohli, AB de Villiers,...","JD Ryder, TD Paine, MK Pandey, Yuvraj Singh, R..."
330,Indian Premier League,2013,9.0,09-04-2013,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,...,SJA Taufel,CK Nandan,KN Ananthapadmanabhan,T20,20,6,male,club,"MA Agarwal, CH Gayle, V Kohli, AB de Villiers,...","PA Reddy, PA Patel, KC Sangakkara, CL White, N..."
342,Indian Premier League,2013,21.0,16-04-2013,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,...,VA Kulkarni,K Srinath,KN Ananthapadmanabhan,T20,20,6,male,club,"CH Gayle, KL Rahul, V Kohli, AB de Villiers, A...","DA Warner, V Sehwag, MC Juneja, DPMD Jayawarde..."
391,Indian Premier League,2013,70.0,18-05-2013,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,...,RJ Tucker,S Das,KN Ananthapadmanabhan,T20,20,6,male,club,"V Kohli, CH Gayle, AB de Villiers, MC Henrique...","MEK Hussey, M Vijay, SK Raina, DJ Bravo, MS Dh..."
508,Indian Premier League,2015,52.0,15-05-2015,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,...,HDPK Dharmasena,K Srinath,A Nand Kishore,T20,20,6,male,club,"DA Warner, S Dhawan, MC Henriques, EJG Morgan,...","CH Gayle, V Kohli, AB de Villiers, Mandeep Sin..."
535,Indian Premier League,2016,19.0,24-04-2016,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,...,BNJ Oxenford,KN Ananthapadmanabhan,A Deshmukh,T20,20,6,male,club,"DR Smith, BB McCullum, SK Raina, KD Karthik, R...","V Kohli, SR Watson, AB de Villiers, KL Rahul, ..."
551,Indian Premier League,2016,35.0,07-05-2016,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rising Pune Supergiants,Royal Challengers Bangalore,field,...,BNJ Oxenford,A Nand Kishore,YC Barde,T20,20,6,male,club,"V Kohli, KL Rahul, AB de Villiers, SR Watson, ...","AM Rahane, UT Khawaja, SS Tiwary, MS Dhoni, NL..."
564,Indian Premier League,2016,48.0,16-05-2016,Kolkata,Eden Gardens,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,A Nand Kishore,BNJ Oxenford,YC Barde,T20,20,6,male,club,"RV Uthappa, G Gambhir, MK Pandey, YK Pathan, A...","CH Gayle, V Kohli, AB de Villiers, SR Watson, ..."
566,Indian Premier League,2016,50.0,18-05-2016,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,...,M Erasmus,K Bharatan,A Deshmukh,T20,20,6,male,club,"CH Gayle, V Kohli, AB de Villiers, KL Rahul, S...","M Vijay, HM Amla, WP Saha, DA Miller, Gurkeera..."
572,Indian Premier League,2016,56.0,22-05-2016,Raipur,Shaheed Veer Narayan Singh International Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,BNJ Oxenford,VK Sharma,YC Barde,T20,20,6,male,club,"Q de Kock, RR Pant, KK Nair, SV Samson, SW Bil...","CH Gayle, V Kohli, AB de Villiers, KL Rahul, S..."
730,Indian Premier League,2019,35.0,19-04-2019,Kolkata,Eden Gardens,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,...,Nitin Menon,AY Dandekar,K Srinath,T20,20,6,male,club,"PA Patel, V Kohli, AD Nath, MM Ali, MP Stoinis...","CA Lynn, SP Narine, Shubman Gill, RV Uthappa, ..."
780,Indian Premier League,2020/21,25.0,10-10-2020,Unknown,Dubai International Cricket Stadium,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,...,PR Reiffel,AY Dandekar,YC Barde,T20,20,6,male,club,"D Padikkal, AJ Finch, V Kohli, AB de Villiers,...","SR Watson, F du Plessis, AT Rayudu, N Jagadees..."
942,Indian Premier League,2022,67.0,19-05-2022,Mumbai,"Wankhede Stadium, Mumbai",Gujarat Titans,Royal Challengers Bangalore,Gujarat Titans,bat,...,GR Sadashiv Iyer,Navdeep Singh,Tapan Sharma,T20,20,6,male,club,"WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ...","V Kohli, F du Plessis, GJ Maxwell, KD Karthik,..."
969,Indian Premier League,2023,20.0,15-04-2023,Bengaluru,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bangalore,Delhi Capitals,Delhi Capitals,field,...,MV Saidharshan Kumar,MA Gough,Abhijit Bhattacharya,T20,20,6,male,club,"V Kohli, F du Plessis, MK Lomror, GJ Maxwell, ...","DA Warner, PP Shaw, MR Marsh, YV Dhull, MK Pan..."
1014,Indian Premier League,2023,65.0,18-05-2023,Hyderabad,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,VK Sharma,HAS Khalid,VM Dhokre,T20,20,6,male,club,"T Natarajan, Abhishek Sharma, RA Tripathi, AK ...","V Kohli, F du Plessis, GJ Maxwell, MG Bracewel..."
1029,Indian Premier League,2024,6.0,25-03-2024,Bengaluru,"M Chinnaswamy Stadium, Bengaluru",Punjab Kings,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,...,MV Saidharshan Kumar,BNJ Oxenford,M Krishnadas,T20,20,6,male,club,"Arshdeep Singh, S Dhawan, JM Bairstow, P Simra...","Yash Dayal, V Kohli, F du Plessis, C Green, RM..."
1081,Indian Premier League,2024,58.0,09-05-2024,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Punjab Kings,Punjab Kings,field,...,HAS Khalid,VK Sharma,Bhavesh Patel,T20,20,6,male,club,"Yash Dayal, V Kohli, F du Plessis, WG Jacks, R...","V Kaverappa, P Simran Singh, JM Bairstow, RR R..."
1131,Indian Premier League,2025,37.0,20-04-2025,Mohali,Maharaja Yadavindra Singh International Cricke...,Punjab Kings,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,...,MV Saidharshan Kumar,Nitin Menon,M Krishnadas,T20,20,6,male,club,"Harpreet Brar, Priyansh Arya, P Simran Singh, ...","Suyash Sharma, PD Salt, V Kohli, D Padikkal, R..."
1202,Indian Premier League,2026,34.0,24-04-2026,Bengaluru,"M Chinnaswamy Stadium, Bengaluru",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,...,J Madanagopal,UV Gandhe,K Kelkar,T20,20,6,male,club,"R Tewatia, B Sai Sudharsan, Shubman Gill, JC B...","Suyash Sharma, JG Bethell, V Kohli, D Padikkal..."
1225,Indian Premier League,2026,57.0,13-05-2026,Raipur,Shaheed Veer Narayan Singh International Stadi...,Kolkata Knight Riders,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,...,R Pandit,TM Srivastava,KM Gandhi,T20,20,6,male,club,"SR Dubey, AM Rahane, FH Allen, A Raghuvanshi, ...","JA Duffy, JG Bethell, V Kohli, D Padikkal, RM ..."
1242,Indian Premier League,2026,NaN,31-05-2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,...,Nitin Menon,J Madanagopal,VK Sharma,T20,20,6,male,club,"M Prasidh Krishna, B Sai Sudharsan, Shubman Gi...","JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Pat..."